name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - run: ls
    - run: ls $(pwd)
    - name: Build the Docker image
      run: docker run --volume $(pwd):/repo --volume /home/runner:/output 'mcr.microsoft.com/oryx/build:latest' oryx build /repo --output /output
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: /home/runner