name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - run: ls
    - run: mkdir -p /home/runner/outputfolder
    - uses: jikuma/githubaction@v6-release
      env:
        ACTIONS_RUNNER_DEBUG: 'true'
      with:
        operation: 'create a release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release_title: 'Release from Test4'
        release_note: 'its a release node'
        asset_filepath: './CHANGELOG.md'
        tag_name: v0.1.GITHUB_SHORT_SHA
       