name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - run: ls
    - run: ls $(pwd)
    - run: mkdir -p /home/runner/outputfolder
    - uses: jikuma/githubaction@v3-release
      with:
        operation: 'create a release'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release_title: 'Release from Test1'
        release_note: 'its a release node1'
        asset_filepath: './CHANGELOG.md'
        tag_name: 'Test1'